url: http://imengineer.in
name: i'm Engineerin'
description: Primarily a blog about software development
title: Simon Campbell's blog
email: simon.s.campbell@gmail.com
baseurl: ""
twitter_username: simon2k6
github_username:  Simon-Campbell

# Build settings
markdown: kramdown